/*
-- Query: SELECT * FROM generation.Countries
LIMIT 0, 1000

-- Date: 2020-02-26 13:56
*/

INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (1,	'Afghanistan', 'AFG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (2,	'Albania', 'ALB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (3,	'Algeria', 'ALG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (4,	'Andorra', 'AND');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (5,	'Angola', 'ANG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (6,	'Antigua', 'ANT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (7,	'Argentina', 'ARG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (8,	'Armenia', 'ARM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (9,	'Australia', 'AUS');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (10,	'Austria', 'AUT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (11,'Azerbaijan', 'AZE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (12,	'Bahamas','BAH');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (13,	'Bahrain','BAR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (14,	'Bangladesh','BAN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (15,	'Barbados','BAR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (16,	'Belarus','BLR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (17,	'Belgium', 'BEL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (18,	'Belize', 'BLZ');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (19,	'Benin','BEM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (20,	'Bhutan', 'BHU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (21,	'Bolivia', 'BOL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (22,	'Bosnia and Herzegovina', 'BOH');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (23,	'Botswana', 'BOT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (24,	'Brazil', 'BRA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (25,	'Brunei', 'BRU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (26,	'Bulgaria', 'BUL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (27,	'Burkina Faso', 'BUF');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (28,	'Burundi', 'BUR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (29,	'Côte d Ivoire','CIV');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (30,	'Cabo Verde', 'CVE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (31,	'Cambodia', 'CMB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (32,	'Cameroon','CAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (33,	'Canada', 'CAN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (34,	'Central African Republic', 'CAP');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (35,	'Chad', 'CHA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (36,	'Chile', 'CHL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (37,	'China','CHI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (38,	'Colombia', 'COL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (39,	'Comoros','COM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (40,	'Congo', 'CON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (41,	'Costa Rica', 'COS');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (42,	'Croatia', 'CRO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (43,	'Cuba','CUB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (44,	'Cyprus', 'CYP');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (45,	'Czech Republic', 'CZE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (46,	'Democratic Republic of the Congo', 'DRC');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (47,	'Denmark', 'DEN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (48,	'Djibouti', 'DJI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (49,	'Dominica','DON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (50,	'Dominican Republic', 'DOM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (51,	'Ecuador', 'ECU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (52,	'Egypt', 'EGY');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (53,	'El Salvador', 'SAL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (54,	'Equatorial Guinea', 'EQG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (55,	'Eritrea', 'ERI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (56,	'Estonia','EST');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (57,	'Eswatini', 'ESW');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (58,	'Ethiopia', 'ETH');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (59,	'Fiji', 'FIJ');	
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (60,	'Finland', 'FIN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (61,	'France', 'FRA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (62,	'Gabon', 'GAB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (63,	'Gambia', 'GAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (64,	'Georgia', 'GEO');	
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (65,	'Germany','GER');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (66,	'Ghana','GHA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (67,	'Greece','GRE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (68,	'Grenada', 'GRN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (69,	'Guatemala','GUA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (70,	'Guinea','GUI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (71,	'Guinea-Bissau','GUB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (72,	'Guyana','GUY');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (73,	'Haiti','HAI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (74,	'Holy See','HSE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (75,	'Honduras','HON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (76,	'Hungary','HUN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (77,	'Iceland','ICE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (78,	'India','IND');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (79,	'Indonesia','INO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (80,	'Iran','IRN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (81,	'Iraq', 'IRQ');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (82,	'Ireland','IRE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (83,	'Israel','ISR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (84,	'Italy','ITA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (85,	'Jamaica','JAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (86,	'Japan','JPN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (87,	'Jordan','JOR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (88,	'Kazakhstan', 'KAZ');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (89,	'Kenya','KEN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (90,	'Kiribati','KIR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (91,	'Kuwait','KUW');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (92,	'Kyrgyzstan','KYR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (93,	'Laos','LAO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (94,	'Latvia','LAT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (95,	'Lebanon','LEB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (96,	'Lesotho','LES');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (97,	'Liberia','LIR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (98,	'Libya','LBY');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (99,	'Liechtenstein', 'LIE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (100,	'Lithuania', 'LIT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (101,	'Luxembourg','LUX');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (102,	'Madagascar','MAD');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (103,	'Malawi','MAW');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (104,	'Malaysia','MAL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (105,	'Maldives','MLD');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (106,	'Mali','MLI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (107,	'Malta','MAL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (108,	'Marshall Islands','MAI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (109,	'Mauritania', 'MAU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (110,	'Mauritius','MAR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (111,	'Mexico','MEX');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (112,	'Micronesia','MIC');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (113,	'Moldova','MOL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (114,	'Monaco','MNC');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (115,	'Mongolia','MNG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (116,	'Montenegro','MON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (117,	'Morocco','MOR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (118,	'Mozambique','MOZ');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (119,	'Myanmar','MYA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (120,	'Namibia','NAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (121,	'Nauru','NAU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (122,	'Nepal','NEP');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (123,	'Netherlands','NED');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (124,	'New Zealand','NZE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (125,	'Nicaragua', 'NIC');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (126,	'Niger','NGR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (127,	'Nigeria','NIG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (128,	'North Korea','NKO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (129,	'North Macedonia','NMA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (130,	'Norway','NOR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (131,	'Oman','OMA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (132,	'Pakistan','PAK');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (133,	'Palau','PAL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (134,	'Palestine State','PAS');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (135,	'Panama','PAN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (136,	'Papua New Guinea','PNG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (137,	'Paraguay','PAR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (138,	'Peru','PER');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (139,	'Philippines','PHI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (140,	'Poland','POL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (141,	'Portugal','POR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (142,	'Qatar','QAT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (143,	'Romania','ROM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (144,	'Russia','RUS');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (145,	'Rwanda','RWA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (146,	'Saint Kitts and Nevis','SKN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (147,	'Saint Lucia','STL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (148,	'Saint Vincent and the Grenadines','SVG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (149,	'Samoa','SAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (150,	'San Marino','SMA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (151,	'Sao Tome and Principe','STP');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (152,	'Saudi Arabia','SDA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (153,	'Senegal','SEN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (154,	'Serbia', 'SER');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (155,	'Seychelles', 'SEY');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (156,	'Sierra Leone',	'SLE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (157,	'Singapore','SIN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (158,	'Slovakia','SLK');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (159,	'Slovenia','SLO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (160,	'Solomon Islands','SIS');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (161,	'Somalia', 'SON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (162,	'South Africa','SAF');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (163,	'South Korea', 'SKO');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (164,	'South Sudan','SSU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (165,	'Spain','SPA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (166,	'Sri Lanka','SRL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (167,	'Sudan','SUD');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (168,	'Suriname','SUR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (169,	'Sweden','SWE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (170,	'Switzerland', 'SWI');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (171,	'Syria','SYR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (172,	'Tajikistan','TAJ');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (173,	'Tanzania','TAN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (174,	'Thailand', 'THA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (175,	'Timor-Leste', 'TIL');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (176,	'Togo', 'TOG');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (177,	'Tonga', 'TON');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (178,	'Trinidad and Tobago', 'TRT');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (179,	'Tunisia', 'TUN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (180,	'Turkey', 'TUR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (181,	'Turkmenistan','TUR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (182,	'Tuvalu', 'TUV');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (183,	'Uganda', 'UGA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (184,	'Ukraine', 'UKR');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (185,	'United Arab Emirates', 'UAE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (186,	'United Kingdom', 'UK');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (187,	'United States of America', 'USA');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (188,	'Uruguay','URU');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (189,	'Uzbekistan', 'UZB');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (190,	'Vanuatu', 'VAN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (191,	'Venezuela', 'VEN');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (192,	'Vietnam', 'VIE');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (193,	'Yemen', 'YEM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (194,	'Zambia', 'ZAM');
INSERT INTO `Countries` (`idCountries`,`Name`,`Code`) VALUES (195,	'Zimbabwe', 'ZIM');


